# Generated by Django 3.2.5 on 2022-01-04 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0003_user_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoBalancerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loadbalancer_name', models.TextField()),
                ('loadbalancer_tag', models.CharField(max_length=1000)),
                ('minimun_droplets', models.IntegerField()),
                ('maximum_droplets', models.IntegerField()),
                ('droplet_tag', models.CharField(max_length=1000)),
                ('threshold_CPU', models.IntegerField()),
                ('threshold_Load1', models.IntegerField()),
                ('threshold_load5', models.IntegerField()),
                ('threshold_load15', models.IntegerField()),
            ],
        ),
    ]
