# Generated by Django 3.2.5 on 2022-01-04 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0004_autobalancermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autobalancermodel',
            name='threshold_CPU',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='autobalancermodel',
            name='threshold_Load1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='autobalancermodel',
            name='threshold_load15',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='autobalancermodel',
            name='threshold_load5',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
