# Generated by Django 3.2.5 on 2022-01-04 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0005_auto_20220104_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='autobalancermodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='autobalancermodel',
            name='is_runing',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
