# Generated by Django 3.2.5 on 2022-01-06 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0006_auto_20220104_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='autobalancermodel',
            name='key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_user.apikeymodel'),
        ),
    ]
